// <auto-generated />
using System;
using Fiap.Api.Coletas.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Api.Coletas.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240620230319_Addcoleta")]
    partial class Addcoleta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.Coletas.Models.coletaModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_coleta");

                    b.Property<string>("Endereco")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("endereco");

                    b.Property<string>("Gravidade")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("gravidade");

                    b.Property<TimeSpan>("HoraColeta")
                        .HasColumnType("INTERVAL DAY(8) TO SECOND(7)")
                        .HasColumnName("hora_coleta");

                    b.HasKey("Id");

                    b.ToTable("tb_Coletas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
